name: Continues Deployment

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        run: npm run deploy
